server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  zipkin:
    #下载zipkin-server-2.12.9-exe.jar，在本地使用java -jar启动后，
    #默认访问端口9411，访问http://localhost:9411/zipkin/ 即可
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于 0 到 1 之间，1 则表示全部采集
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ColorXJH
    password: 2012WananXJH

eureka:
  client:
    #表示是否将自己注册进eurekaServer,默认为true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认为true,单节点无所谓，集群必须设置为true,才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版
      defaultZone: http://slave1:7001/eureka
      #集群版
      #defaultZone: http://slave1:7001/eureka,http://slave2:7001/eureka
  instance:
    instance-id: payment8001
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位是秒（默认30）
    #lease-renewal-interval-in-seconds: 20
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒，默认为90，超时将剔除服务
    #lease-expiration-duration-in-seconds: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.master.entity





