server:
  port: 9527
spring:
  application:
    name: cloud-gateway9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route #payment_route 路由的id,没有固定得规则但要求唯一，建议配合服务名
          uri: http://localhost:8001 #匹配后提供服务的路由地址
          #uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/query/**  #断言，路径相匹配的进行路由
        - id: payment-route2
          #uri的协议为lb,表示启用gateway的负载均衡功能
          uri: lb://cloud-payment-service #启用我们提供服务的负载均衡
          #predicate为了实现一组规则，让请求过来找到对应的route进行处理
          predicates:
            - Path=/payment/getPort
            #- After=2020-12-21T15:51:37.485+08:00[Asia/Shanghai]
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Cookie=username,zhangshuai #并且Cookie是username=zhangshuai才能访问
            #- Host=**.master.com
            #- Method=GET
            #- Query=username, \d+ #要有参数名称并且是正整数才能路由
eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://slave1:7001/eureka/
